### ISSUE TITLE
Source block incapable of writing to more than one block

### ISSUE THREAD

**Issue by Merith-TK** [tweaked-programs/cccbridge#1]
![image](https://user-images.githubusercontent.com/10422110/183124302-c1b903e8-1980-4577-8d19-6e997b5d9288.png)
![image](https://user-images.githubusercontent.com/10422110/183124363-c341f6ae-bbbc-4828-ad0a-ff7fa928a7fe.png)
![image](https://user-images.githubusercontent.com/10422110/183124390-e5471d18-2ac2-467b-8e23-04d3454a082f.png)

utilizing an nametag scales properly
![image](https://user-images.githubusercontent.com/10422110/183124461-a6f9f28a-48ed-4dff-9ec1-e71a08cb5d6c.png)

**Comment by SammyForReal** [comment]
The current display size only gets syncronized when the display link transfers data. So when you load the peripheral, either send a redstone signal to the display link, click the checkmark in the UI or wait about 5 seconds where it does it by itself. Read more at:
https://github.com/tweaked-programs/cccbridge/wiki/Source-Block
