### ISSUE TITLE
Ticking Block Entity server start

### ISSUE THREAD

**Issue by PABessero** [tweaked-programs/cccbridge#11]
**Description**
After playing a bit with the Target block, I ended up restarting the server to update the pack from 1.0.2 to 1.1.0 (Stoneblock 3) and it wont launch until i switch Forge to remove Erroring tile entities.
It doesnt actually remove the block, however the server does launch, but interracting with the computer then crashes the server.

**To Reproduce**
Computer connected with no startup program (so no program should have been running)
2 target block: 
- 1 connected to a train station
- 1 connected to 3 tunnels

**Software (please complete the following information):**
 - Minecraft Version: 1.18.2
 - Mod Version 1.3
 - ModLoader Forge
 - Server running on Linux (Ubuntu)

ModPack: Stoneblock 3

**Comment by PABessero** [comment]
Crash on startup:
[crash-2022-11-07_09.17.38-server.txt](https://github.com/tweaked-programs/cccbridge/files/9950147/crash-2022-11-07_09.17.38-server.txt)

**Comment by PABessero** [comment]
Crash upon clicking the computer
[crash-2022-11-07_09.25.52-server.txt](https://github.com/tweaked-programs/cccbridge/files/9950148/crash-2022-11-07_09.25.52-server.txt)

**Comment by Luke1505** [comment]
I'll look into it later thx

**Comment by SammyForReal** [comment]
Hey, I also looked at it now and found the error, I'll publish a patch for it later

**Comment by SammyForReal** [comment]
Got fixed via commit b97db00c364fdc0a7988fb56ca625a727816de14 and published under [v1.3.1](https://github.com/tweaked-programs/cccbridge/releases/tag/v1.3.1)
