### ISSUE TITLE
target block question

### ISSUE THREAD

**Issue by Mjam-0** [tweaked-programs/cccbridge#13]
is it possible to get data with the display link, send it to a target block, and have that data be written using monitor.write()?

**Comment by Luke1505** [comment]
Yes it is

**Comment by Luke1505** [comment]
You can get the Lines you want and monitor.wirte(target_block.getLine(XYZ))

https://github.com/tweaked-programs/cccbridge/wiki/Target-Block

**Comment by SammyForReal** [comment]
As there is no further question, this will be interpreted as answered.
