### ISSUE TITLE
RedRouter block has no support for os.pullevent("redstone")

### ISSUE THREAD

**Issue by JHDev2006** [tweaked-programs/cccbridge#17]
**Description**
as title says, redrouter block has no way of supplying a redstone input event

**To Reproduce**
redstone input to redrouter, 
"while true do
os.pullevent("redstone")
print("yay")"

**Expected behavior**
supplys the event required for this

**Screenshots**
*If applicable, add screenshots to help explain your problem here.*

**Software (please complete the following information):**
 - Minecraft Version 1.18.2
 - Mod Version 1.3.1
 - ModLoader Forge

**Comment by SammyForReal** [comment]
Hey, thanks for telling us! I will try to implement that.

**Comment by SammyForReal** [comment]
Fixed in f4b9eca1669eafa4eabe294e6552881bcd911319

**Comment by Tcheikovski** [comment]
Hi ! Thanks for the implementation, but it only works in 1.19
By any chance, are you goind to add this in a 1.18 version ?

**Comment by SammyForReal** [comment]
Hm, good question. It was originally not planed to update the 1.18 anymore. But the version is still _(kind of)_ actively used, so we probably will backport some updates with major changes.
