### ISSUE TITLE
Train observer compatiblility as a peripheral

### ISSUE THREAD

**Issue by stacode123** [tweaked-programs/cccbridge#18]
**Description**
*A clear and concise description of what the idea is.
Like with train stations that would allow for reading statistics about the train without the train stopping at a train station

**Comment by Luke1505** [comment]
for reference which features would you like to have in whithin that peripheral so i now what it whished for and has priority ?

**Comment by stacode123** [comment]
i taught maybe:
-train name
-Speed? i dont think thats possible
-next station/schedule extraction maybe?

**Comment by Luke1505** [comment]
Speed and schedule ill look into it 👍🏻 thanks for the quick reply

**Comment by stacode123** [comment]
I recently was thing about it and I have some uses.
Mostly getting info about a train. Without it stopping.

**Comment by Luke1505** [comment]
I am Working on it but getting the Data with the observer is not easy/ i dont even know if its possible so you'll have to wait a bit longer

**Comment by Luke1505** [comment]
FYI, I currently am at that point where I know that a train Passes/enters/leaves the area of the Train Observer but stuff like name/speed, etc. I am currently running against a wall. 
I'll keep trying my best but the Next Update to make it Compatible with the newest Create version is currently more important than this.
if you got more ideas please let me know.

Kind Regards
Luke

**Comment by Luke1505** [comment]
After Careful Consideration, we've come to the conclusion that we won't implement this for now.
Because the Train Observer already does specific filter things which then return a Redstone Signal with these functions the Observer is fully functional and not somehow limited to what it could do.
I am sorry.

**Comment by stacode123** [comment]
Yeah ok
