### ISSUE TITLE
Forge 1.19.2

### ISSUE THREAD

**Issue by Kvass134** [tweaked-programs/cccbridge#19]
Please, update a mod to version minecraft 1.19.2 ( forge )

**Comment by SammyForReal** [comment]
I just realized I didn't mention the forge port too. Both versions are in development and almost done ;)
I will keep this one open until I made a pr

**Comment by Kvass134** [comment]
okay:)

**Comment by SammyForReal** [comment]
Forge 1.19.2 now available because of: f4b9eca1669eafa4eabe294e6552881bcd911319
Have fun! ^^
