### ISSUE TITLE
Target and source blocks are not working

### ISSUE THREAD

**Issue by YLlywelyn** [tweaked-programs/cccbridge#21]
I placed a target block next to a computer and tried running `tb = peripheral.wrap("back")`, but when I print the value of `tb` I get nill.

Next, I tried to use the display link on both a source block and a target block but the display link said that both of them are invalid sources/targets.

**Expected behavior**
I expect the blocks to work as descibed on the wiki.

**Software (please complete the following information):**
 - Minecraft Version [e.g. 1.18.2] 1.19.2
 - Mod Version [e.g. 1.2.1] 1.40
 - ModLoader [Forge / Fabric] Fabric

**Comment by SammyForReal** [comment]
Yes, I found out about this *after* releasing it... I will try to fix it today if I get time..
*(I really dont know what I did for it breaking..)*

**Comment by YLlywelyn** [comment]
I hate when that happens, especially when there's no obvious reason it's broken 😐
I shall await the next version then

**Comment by SammyForReal** [comment]
Fixed in 7ada8354acb3acf95596cdbbf70da4ddad9db90e
