### ISSUE TITLE
Train Station block error

### ISSUE THREAD

**Issue by SvCpu** [tweaked-programs/cccbridge#23]
**Description**
I encountered a game crash and could not load the world when I used a computer to execute assemble() or disassemble() on a Train Station block to assemble or disassemble trains.
This error prevents worlds from mineservers from being able to join

**To Reproduce**
1. join multiplayer game
2. Place a Train Station block
3. Connect it to a computer
4. Run command assemble() or disassemble() on the Train Station block
5. See error

**Expected behavior**
I expected the Train Station block to work normally and allow me to assemble or disassemble trains without crashing the game or preventing me from loading the world.

**Software (please complete the following information):**
 - Minecraft Version 1.19.2
 - Mod Version 1.4.1
 - ModLoader Fabric 0.14.14
 - Create Mod Version 0.5g-796
 - CC: Restitched Mod Version 1.101.2

The above content is translated by Google Translate

**Comment by SvCpu** [comment]
By the way this error is not guaranteed to occur

**Comment by SammyForReal** [comment]
Thanks for the bug report. What error message do you get? Can you maybe upload the logs too from the moment it happened?

**Comment by Luke1505** [comment]
To make sure : is at the Train Station a Train or isn't there one ?

**Comment by SvCpu** [comment]
There are trains at the railway station, and they have stopped at the station.
[2023-03-09-4.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976875/2023-03-09-4.log.gz)
[2023-03-09-5.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976876/2023-03-09-5.log.gz)
[2023-03-09-1.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976877/2023-03-09-1.log.gz)
[2023-03-09-2.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976878/2023-03-09-2.log.gz)
[2023-03-09-3.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976879/2023-03-09-3.log.gz)
This is the server's log for the day
[crash-2023-03-09_20.16.09-client.txt](https://github.com/tweaked-programs/cccbridge/files/10976887/crash-2023-03-09_20.16.09-client.txt)
[crash-2023-03-09_19.25.02-client.txt](https://github.com/tweaked-programs/cccbridge/files/10976888/crash-2023-03-09_19.25.02-client.txt)
This is the client crash record
[2023-03-09-1.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976894/2023-03-09-1.log.gz)
[2023-03-09-2.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976895/2023-03-09-2.log.gz)
[2023-03-09-3.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976896/2023-03-09-3.log.gz)
[2023-03-09-4.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976897/2023-03-09-4.log.gz)
[2023-03-09-5.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976898/2023-03-09-5.log.gz)
[2023-03-09-6.log.gz](https://github.com/tweaked-programs/cccbridge/files/10976899/2023-03-09-6.log.gz)
This is the client's log for the day
Sorry the log might be a bit much because I forgot when it happened

**Comment by Luke1505** [comment]
Thanks for the Provided information.
I am going to get that fixed and hopefully it's in the next update.

**Comment by GeggsLegs** [comment]
This issue also happened on my server running forge. It was a while ago so I don't think I have the logs anymore but it appeared that the crash had to do with the render engine. The crash happened with oculus + rubidium and without. I was able to recover the world by teleporting the player away from the train from the server console. Then the client could use "/create trains" to view and remove the bugged train.

**Comment by Luke1505** [comment]
To the Last point : Was this with the newest version of CC:C Bridge or an older one?

**Comment by SammyForReal** [comment]
> This issue also happened on my server running forge. It was a while ago so I don't think I have the logs anymore but it appeared that the crash had to do with the render engine. The crash happened with oculus + rubidium and without. I was able to recover the world by teleporting the player away from the train from the server console. Then the client could use "/create trains" to view and remove the bugged train.

That is weird. We have nothing to do with the rendering engine, we didn't modify any of it.

**Comment by SvCpu** [comment]
>To the Last point : Was this with the newest version of CC:C Bridge or an older one?

CC:C Bridge fabric 1.4.1

**Comment by Luke1505** [comment]
I am Not able to reproduce the error, could you try again and send a picture of the blocks how they are setup and then the error log of that run 
Thanks

**Comment by SvCpu** [comment]
I reproduce this error using server mirror
The first video is the error reproduction
The 2nd video is unable to reach the server after an error
Only the client crashes when an error occurs

[ClientModList.txt](https://github.com/tweaked-programs/cccbridge/files/11110713/ClientModList.txt)
[ServerModList.txt](https://github.com/tweaked-programs/cccbridge/files/11110714/ServerModList.txt)

https://youtu.be/p9MIybM0SM0
https://youtu.be/ZT06XldrDmw
These videos may not be viewable while YouTube is processing them

client log
[2023-03-30-2.log](https://github.com/tweaked-programs/cccbridge/files/11110745/2023-03-30-2.log)
[2023-03-30-1.log](https://github.com/tweaked-programs/cccbridge/files/11110746/2023-03-30-1.log)
server log
[latest.log](https://github.com/tweaked-programs/cccbridge/files/11110751/latest.log)

**Comment by Luke1505** [comment]
Have you tried only using the necessary mods for cccbridge?

**Comment by Szedann** [comment]
I'm also having this issue - it appears that the bug happens only when the train has a blaze burner attached.
[Crash Report](https://bytebin.lucko.me/yuERqDgDP1)

**Comment by Luke1505** [comment]
Hi, i tried fixxing it could you try using this version -> 
[JarFiles.zip](https://github.com/tweaked-programs/cccbridge/files/11347687/JarFiles.zip)

**Comment by SvCpu** [comment]
This does fix the crash, but loses the train station as a peripheral (´。＿。｀)

**Comment by Luke1505** [comment]
Wait, what? When I tested It worked ... Huh. Unfortunately I'll am on vacation for 2 Weeks now so I'll look into it again when I'm back

**Comment by Luke1505** [comment]
Hello again, because the Train assembly and disassembly was taken care of by Create Themselves all our colliding functions will be replaced by theirs but that does not mean we are not adding additional functions to it in the future.
Kind Regards Luke.

**Comment by Luke1505** [comment]
Closed (removed function(implemented by Create themselves))
