### ISSUE TITLE
Switch from CC:R to CC:T in Fabric

### ISSUE THREAD

**Issue by awesomebossdj7** [tweaked-programs/cccbridge#24]
please make a version where its fabric but cc:tweaked and not restitched

(cctweaked fabric vers was revived for switchcraft 3, and I think is better then restitched)

also if this is already a thing, please send me the link, or tell me where its at

thanks

**Comment by awesomebossdj7** [comment]
well i guess schedule this for when create mod 1.19.3 comes out

**Comment by SammyForReal** [comment]
Yeah I have plans to switch to cc:tweaked in fabric. The real question is when are we doing so. _(And like you pointed out the create mod is another factor we have to consider)_

**Comment by SammyForReal** [comment]
Solved in 1.20.1 branch
