### ISSUE TITLE
I made a Russian translate 

### ISSUE THREAD

**Issue by Grigew** [tweaked-programs/cccbridge#27]
(I'm noob in github and don't know where to put it so I'll put it here)

It's 1.19.2

ru_ru.json

{
  "block.cccbridge.source_block": "Блок источник",
  "block.cccbridge.target_block": "Целевой блок",
  "block.cccbridge.redrouter_block": "Ред-Роутер",
  "block.cccbridge.scroller_block": "Панель прокрутки",

  "cccbridge.display_source.source_block_display_source": "Данные, полученные от компьютера",

  "cccbridge.general.unit.scroller": "Маленькое Lua число",

  "subtitles.cccbridge.cage_lock": "Прокрутка заблокирована",
  "subtitles.cccbridge.cage_unlock": "Прокрутка разблокирована"
}

**Comment by SammyForReal** [comment]
Hey, thanks for taking the time making those translations ^^
I will take a deeper look at may them later and add them to the next release.

For now, I'll let this issue open. (Also sorry for taking so long to answer)

**Comment by SammyForReal** [comment]
Hey, I need to request you to update the translations again for the next release, sorry! But it should be done pretty quick.
I will close this issue for now, but you can fork this project, make the changes on your fork and then open a Pull Request here for it! I'm sure you will figure it out.
