### ISSUE TITLE
Create 0.5.1 broke the mod

### ISSUE THREAD

**Issue by ElNico56** [tweaked-programs/cccbridge#28]
**Description**
Mod refuses to load when using the most recent create update

**Software**
 - Minecraft Version 1.19.2
 - Mod Version 1.4.1
 - Create Version 0.5.1b
 - ModLoader Forge

**Comment by SammyForReal** [comment]
Thanks for letting us know!

We are aware that this version has huge changes in the codebase. We also have big plans and will surely update to it.

**Comment by ProNoob135** [comment]
https://github.com/tweaked-programs/cccbridge/pull/32

**Comment by Luke1505** [comment]
fixed with #32
