### ISSUE TITLE
more features pls!

### ISSUE THREAD

**Issue by wangba1129** [tweaked-programs/cccbridge#31]
I'd like to be able to interact with more create mod stuff like funnel's and other blocks' filters, rpm and machine startup and shutdown
I'm sorry that my English is not good, so I used the translation software and couldn't explain it in detail

**Comment by Luke1505** [comment]
Isn't this similar to #47?

**Comment by SammyForReal** [comment]
Although this was before #47 , I will mark this as duplicate, as this one is more detailed about this and other features we have in plan.
Thank you for participating here!
