### ISSUE TITLE
Animatronic refuses to change it's expressions

### ISSUE THREAD

**Issue by BirbIrl** [tweaked-programs/cccbridge#53]
The animatronic is an amazing addition that i'm super happy to see in the pack. I have issues with applying various facial expressions though :(.
It seems that no expressions seem to load. I also am unsure of if this has to do with my performance mods, or if it's a bug that simply comes along with fabric. If this turns out to be a mod compatibility issue i'll try and list my mods/troubleshoot to see what causes it :D 

![2023-07-08_19 11 35](https://github.com/tweaked-programs/cccbridge/assets/74369380/3c2980d8-389c-41df-ab9b-0022f9d68ae3)
![2023-07-08_19 11 38](https://github.com/tweaked-programs/cccbridge/assets/74369380/7fa1acfc-daee-41bb-945f-6f624f163fa2)

 - Minecraft Version 1.19.2
 - Mod Version 1.5.0
 - ModLoader: Fabric

**Comment by SammyForReal** [comment]
Huh, you should always see an facial expression. This smells like an performance mod thingy, could you test this without any performance mods maybe?

**Comment by BirbIrl** [comment]
The culprit - Iris! Almost everyone uses that mod too, so they can run shaders... There also doesn't seem to be a setting that i can toggle to disable this issue. That's the best pointer i can give

**Comment by SammyForReal** [comment]
![grafik](https://github.com/tweaked-programs/cccbridge/assets/53350357/758fcd65-ad03-475b-930d-79dd2180e3cc)
Oh yep, this for sure is an Iris problem.

Installing Indium doesn't help tho... I really don't know how to fix this however... I can only redirect you to [the Iris repository](https://github.com/IrisShaders/Iris), maybe they know more about this?

**Comment by BirbIrl** [comment]
Okay i have no clue how fabric modding looks like - but considering that every other texture loads - what if you made the model's faces a spritesheet and instead of switching between different files, move around the texture field box in a single loooong strip of faces? Is that even possible? I've no clue! But the issue seems to stem from you looking to load files separately after the entity has spawned (?)

**Comment by SammyForReal** [comment]
Its actually quiet simple how I render it. So basically, the block renders an entity and its model. The textures for it get rendered twice however. The first one is for the whole skin. The second one is for the face only and it just gets added on top of it basically.

I *could* make an option that lets you render them at once with the first layer and then this is solved. You would'nt have the glow effect then but better than not seeing the face at all.

Yeah I think I will add an config for this.
Oh and about your theory, I am pretty sure it finds the textures for the faces. Or else you would see a whole pink/black texture on top of the model.

**Comment by ProNoob135** [comment]
I'm curious how other mods handle overlay textures and whether any manage support for glowing and indium/iris simultaneously

**Comment by SammyForReal** [comment]
fixed in 1.20.1 branch
