### ISSUE TITLE
Allow animatronic rotation values above/below +-180

### ISSUE THREAD

**Issue by ProNoob135** [tweaked-programs/cccbridge#58]
There's currently no way(afaik) to smoothly rotate the animatronic around the 180/-180 area, as it will have to jerk all the way around.
Since rotations are global and not relative to the direction the animatronic was placed, this means a south-facing animatronic can't (for example) wiggle it's body back and forth without doing a full rotation.
Allowing "infinite" rotation values will let the bot spiiiin, etc. You'll probably want to cap the max rotation speed.

If unrestrained rotation isn't preferred(slip rings are expensive!), rotation should be relative to placement direction so south facing robots aren't at a disadvantage, and maybe 180/-180 should be at the back to allow even rotation

**Comment by SammyForReal** [comment]
Making the block facable sounds like a good addition, however, I won't remove the bounds. Simultaneously rotations is something I want to get in however for the body.

**Comment by SammyForReal** [comment]
Im closing this now because the Animatronic is facable nowerdays, which is fixing this issue.
