### ISSUE TITLE
Selection Pane (replacing Scroller Pane)

### ISSUE THREAD

**Issue by tizu69** [tweaked-programs/cccbridge#62]
# **Description**
The scroller panes are cool n all, but I feel like they're lacking some features for me to actually implement them in my designs.
- Custom labels instead of lua number (see Brass Funnel)
- pre-/suffix for nums, not visible unless in gui (see Brass Funnel)
- Additional rows (see Pulse Extender)
- Item slots; either item and selection or only one (see Brass Funnel)
- Non-numerical items (see Mechanical Roller; probs without the icon, string only; each item got an id similar to \<select> in html so that you can reference them by id)
- Changing the gap of the focused options (shift)

# **Describe alternatives you've considered**
n/a

**Comment by LeMoonStar** [comment]
I wouldn't neccesairly replace scroller panes, but add the suggested selection panes as an additional block.

**Comment by SammyForReal** [comment]
Woah woah there, for each custom interface you see on a create block, that is it's whole own behaviour class.
That would be a lot of work, doing via their code. This is why each block only has one.
Besides, switching between them would be difficult as well, as those are not really easy to dynamically switch.

At this point I would need to do something custom.

_I actually like the idea of having a way of making easy (and good looking) interfaces. I had this flowing in my mind for a while now._

But I don't think that a "Selection Scroller Pane" is the way.
I would also just use a monitor for more complex stuff at this point.
