### ISSUE TITLE
RedRouter block doesn't fire "redstone" event

### ISSUE THREAD

**Issue by aoxiangtianji** [tweaked-programs/cccbridge#64]
**Description**
As title.

**To Reproduce**
1. Place redrouter block
2. Connect on a advanced computer
3. Run command `os.pullEvent("redstone")`
4. Give the redrouter block a redstone signal
5. Nothing happend

* I also installed advanced periphearals 0.7.30r

**Expected behavior**
Event "redstone" fires.

**Software (please complete the following information):**
 - Minecraft Version 1.19.2
 - Mod Version 1.5.1
 - ModLoader Forge
 - Forge Version 43.2.21

**Comment by SammyForReal** [comment]
Thank you for reporting this. That indeed is not supposed to happen. I will try to fix that

**Comment by SammyForReal** [comment]
Fixed in a59279163fb9d9196e7c0bd14cdedaaecadf95c1

**Comment by elblorenz32** [comment]
I'd like to reopen this for mc Version 1.20.1 with Forge 47.2.0 and mod version 1.6.3

Behaviour is the same as OP described
