### ISSUE TITLE
mod is on 1.20.1 fabric/quilt even though create does not exist on that version

### ISSUE THREAD

**Issue by Madeline69a** [tweaked-programs/cccbridge#68]
**Description**
minecraft doesnt load

**To Reproduce**
1. install any 1.20.1 version
2. try to open the game
3. see error

**Expected behavior**
the game is supposed to launch like normal and function

**Screenshots**
the crash
![image](https://github.com/tweaked-programs/cccbridge/assets/133543130/1e443524-a722-412e-9435-c578a7055776)

**Software (please complete the following information):**
 - Minecraft Version [e.g. 1.20.1]
 - Mod Version [e.g. 1.6.2b mc 1.20.1]
 - ModLoader [Quilt]
 - CC: Tweaked [1.107.0]

**Comment by SammyForReal** [comment]
Create Fabric _does_ exist on that version. There is just no release for the distribution platforms, so you gotta build it by yourself or download it via their maven.

You could also wait for it to be done and ready.

CC:C Bridge is hard dependent on Create.
