### ISSUE TITLE
CC:C bridge breaks item filters on funnels, tunnels, etc.

### ISSUE THREAD

**Issue by jellopudding** [tweaked-programs/cccbridge#72]
**Description**
With CC:C bridge installed item filters on create's funnels, tunnels, etc. and settings for valve handles are inoperable.

**To Reproduce**
1. Install CC:C bridge, Create, and other prerequisites
2. Launch the game and create a single player world
3. Place a funnel, tunnel, or other create block that allows filtering
4. attempt to add and item to the blocks filter

**Expected behavior**
The player should be able to place the item in their hand into the funnel/tunnel's filter slot somewhere near the center of the block, they should also be able to set the precise rotation of the valve handle.

**Screenshots**
No filter set, CC:Cb on
![2023-09-02_17 19 47](https://github.com/tweaked-programs/cccbridge/assets/5677453/e0907f7b-1a59-4915-b18b-d9c453087daa)
Attempting to set filter, CC:Cb on
![2023-09-02_17 19 48](https://github.com/tweaked-programs/cccbridge/assets/5677453/1f8ef215-b0a9-446a-b23a-8631a4b7727e)
No filter set, CC:Cb off
![2023-09-02_17 20 21](https://github.com/tweaked-programs/cccbridge/assets/5677453/77cc8bbc-5b7e-4366-93d5-b59a222af7ac) 
Setting filter, CC:Cb off
![2023-09-02_17 20 22](https://github.com/tweaked-programs/cccbridge/assets/5677453/c3a4ac0d-b147-46be-8b78-ab68db2fb410)
Unsetting filter, CC:Cb off
![2023-09-02_17 20 24](https://github.com/tweaked-programs/cccbridge/assets/5677453/af529629-035d-41ae-8dce-90be3b8f361e)
**Software (please complete the following information):**

 - Minecraft Version 1.20.1
 - CC:C Bridge 1.6.2a-fabric
 - Create 0.5.1-d-build,1161+mc1.20.1
 - CC:Tweaked 1.107.0
 - ModLoader Fabric 0.14.22

**Comment by SammyForReal** [comment]
This got fixed in v1.6.2b. _(you are using v1.6.2a)_
Please update.

**Comment by jellopudding** [comment]
> Please update.

please post the update to modrinth

**Comment by SammyForReal** [comment]
Sorry you are right.
I haven't managed to do so in the past days. It's now uploaded on [Modrinth](https://modrinth.com/mod/cccbridge/version/1.6.2b-fabric) _(and soon on CurseForge as well)_!
