### ISSUE TITLE
add afew more Computercraft mod compatible for Station blocks

### ISSUE THREAD

**Issue by DoctorFlux** [tweaked-programs/cccbridge#76]
mainly to get a station block´s coordinates a computer is connected to 
and  what way the arrow is facing on the station block and its track

asking this becuase it could be usefull for CC x Create train programs 

as im making one currently that can do afew things:
-request a passenger train to come from the nearest depot where its parked to a station the player is standing on with a schedule that drive the player to where they wanted : clicked on a monitor where all schedules to all passenger stations is listed

-have a supply/requester item & fluid station somewhat like facotorio logistic  robot works but for create cargo trains made via CC 

and adding those compatible could help alot on that 
and stuff like this do need to know a station´s location and direction 
currently we can only get the station´s name out 

it is mainly so it can get all the info about the station arrow on the track: 
its coordinates, what way it is facing on to computercraft data so it can be doable for computercraft to use that info for CC programs 
![image](https://github.com/tweaked-programs/cccbridge/assets/100806234/c8aee2fd-1e65-4ddf-a845-b815636727e8)

**Comment by SammyForReal** [comment]
Hey!
The train station blocks peripheral is from Create, take a look at [our peripherals wiki](https://cccbridge.tweaked-programs.cc/peripherals/) to see what we over! ^^

We really don't want to mess around with doing peripherals directly in Create blocks, especially if they already made one, as this only leads to more chaos, than there already is.

Anyways, maybe you want to pin those ideas [there](https://github.com/Creators-of-Create/Create/issues)!
I will close this issue for said reasons tho here.

**Comment by DoctorFlux** [comment]
i was thinking to add a method() to this no need to add new blocks or properly edit existing ones
mainly just a way to get the coordinates of 
![image](https://github.com/tweaked-programs/cccbridge/assets/100806234/4dc38081-62b4-4a99-9a11-95aef4fac9af)
into a computercraft program without need to manual input it

**Comment by SammyForReal** [comment]
We do not want to manipulate peripherals that Create made for Create Blocks. Open an issue there for this please.
