### ISSUE TITLE
1.20.1 crash with Create: Diesel Generators

### ISSUE THREAD

**Issue by c0gd1s** [tweaked-programs/cccbridge#80]
Mod loads correctly with 440 mods, but conflicts with create diesel generators
https://gist.github.com/c0gd1s/50fbbee0ca129d87609fad8562731012

**Comment by SammyForReal** [comment]
Hey.
There are multiple things I'd like to point out here.

First of: We have a template for bug reports that you just completely ignored.
You also didn't try to reproduce this in an isolated environment. Instead, you just throw this crash report of an modpack within like hundreds of mods here.
You also couldn't wait a full day for me to answer here and reposted this on an thread that has nothing to do with this on curseforge.
And last but not least, where does cccbridge come into part here? The error you are getting has something to do with an mixin by createdieselgenerator and not cccbridge, this mod doesn't even do mixins.

Refer to their GitHub for this report please.
