### ISSUE TITLE
[1.20.1] [Forge 47.2.16] Animatronic not attaching to the computer

### ISSUE THREAD

**Issue by killer2gudpl** [tweaked-programs/cccbridge#85]
**Description**
Animatronic cannot get attached to the computer at all, meaning it cannot be used.

**To Reproduce**
1. Place the Advanced Computer
2. Launch lua
3. Type "peripheral.wrap(side)"
4. "Nil" comes up meaning it is unsuccessful in connecting to the peripheral.

**Expected behavior**
Computer attaches to the animatronic, enabling the usage of its functions.

**Screenshots**
![image](https://github.com/tweaked-programs/cccbridge/assets/135867890/056ba042-2d7b-4018-9e45-eb62ddfacc89)

**Software (please complete the following information):**
 - Minecraft Version - 1.20.1
 - Mod Version - v1.6.3
 - ModLoader - Forge 47.2.16

**Mod list:**
 - Create 0.5.1.f
 - CC:C Bridge 1.6.3
 - CC: Tweaked 1.109.0

**Comment by SammyForReal** [comment]
The animatronic only can be attatched from below.
Meaning in your example, the animatronic would stand on top of the computer.

I should update the wiki to make this clear, sorry!
