### ISSUE TITLE
Opening inventory in creative on Forge 1.20.1 crashes the game 

### ISSUE THREAD

**Issue by hank-en-henk** [tweaked-programs/cccbridge#93]
**Description**
Opening inventory in creative on Forge 1.20.1 crashes the game. This triggers a `NullPointerException` for `Registry Object not present: cccbridge:source_block`.

**To Reproduce**
1. Go into creative
2. Open inventory
3. Crash

**Expected behavior**
Opening the inventory in creative does not crash the game

**Screenshots**
*If applicable, add screenshots to help explain your problem here.*

**Software (please complete the following information):**
 - Minecraft Version: 1.20.1
 - Mod Version: 1.6.3
 - ModLoader: Forge

**Crashlog**
https://mclo.gs/l8rK6RJ

**Comment by SammyForReal** [comment]
Hello!

May I ask for the full log?
Have you also tested this in an isolated environment? Because I can't reproduce this issue.

**Comment by SammyForReal** [comment]
I got the full logs through my DMs.
Turns out the used custom modpack here was causing this issue, because some mods were missing on server side.
